import { ModelLoader } from './ModelLoader';
import { InstanceData, AnimationOptions, AnimationEventCallback } from './types';
export declare class AnimationController {
    private modelLoader;
    private useWorker;
    private workerManager;
    private instanceCache;
    private animationCallbacks;
    private previousAnimationTimes;
    private previousAnimationNames;
    private instanceSequence;
    constructor(modelLoader: ModelLoader);
    setUseWorker(enabled: boolean): Promise<void>;
    cacheModelInWorker(modelId: string): Promise<void>;
    private fastSceneTraverse;
    private updateNodeLocalTransforms;
    setBindPose(instance: InstanceData): void;
    private updateAnimationMatricesFromTransforms;
    updateAnimation(instance: InstanceData, deltaTime: number): void;
    private applyWorkerResults;
    private updateNodeHierarchyTransforms;
    private maxDuration;
    private updateTime;
    private updateNodeAnimationTransforms;
    private updateNodeSkinningMatrices;
    private updateInstanceCache;
    private updateBoneMatricesSync;
    private updateBoneMatricesMainThread;
    private mat4FromTypedArray;
    private findKeyframeIndices;
    private interpolateValues;
    startAnimation(instance: InstanceData, animationName: string, options?: AnimationOptions): void;
    private captureCurrentTransforms;
    private packTransformsForWorker;
    stopAnimation(instance: InstanceData): void;
    invalidateCache(instanceId: number): void;
    registerAnimationCallback(instanceId: number, callback: AnimationEventCallback): void;
    unregisterAnimationCallback(instanceId: number): void;
    private fireAnimationEvent;
}
//# sourceMappingURL=AnimationController.d.ts.map